language: node_js
node_js:
  - "stable"
dist: trusty
sudo: true

install:
- npm install -g @angular/cli

before_script:
- cd DIYHacks
# - npm set registry https://resgitry.npmjs.org/
- sudo npm --registry http://registry.node-modules.io/ install
cache:
  directories:
    - node_modules/
    - DIYHacks/node_modules

addons:
  chrome: stable

script:
  #- npm run lint
  - npm run test
  #- npm run build
  #- xvfb-run npm run e2e
