language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

install:
- npm install -g @angular/cli

before_script:
- cd DIYHacks
- npm install
cache:
  directories:
    - DIYHacks/node_modules

addons:
  chrome: stable

script:
  #- npm run lint
  - npm run test
  #- npm run build
  #- xvfb-run npm run e2e
