language: node_js
node_js:
  - "stable"
dist: trusty
sudo: true

install:
- npm install -g @angular/cli

before_script:
- cd DIYHacks
- npm set registry https://resgitry.npmjs.org/
- npm i
# cache:
#   directories:
#     - DIYHacks/node_modules

addons:
  chrome: stable

script:
  #- npm run lint
  - npm run test
  #- npm run build
  #- xvfb-run npm run e2e
